name: build_pr

on:
  pull_request_target:
    branches: [ master ]

jobs:
  build_pr:
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Checkout baserom
      uses: actions/checkout@v2
      with:
        repository: coderstig/mk64_priv
        token: ${{ secrets.PRIV }}
        path: baserom
    - name: Decrypt baserom
      run: echo ${{ secrets.KEY }} | openssl enc -d -aes-256-cbc -pass stdin -pbkdf2 -in baserom/baserom.us.z64.aes -out baserom.us.z64

    - name: Perform make tools
      run: |
          sudo apt-get install -y build-essential pkg-config git binutils-mips-linux-gnu python3 zlib1g-dev libaudiofile-dev libcapstone-dev
          make -j4 -C tools/
    - name: Extract assets
      run: |
        ./extract_assets.py us
    - name: Build U source
      run: |
        make -j4 VERSION=us VERBOSE=1 COLOR=0ke --jobs
